#:schema https://raw.githubusercontent.com/cedarjs/cedar/packages/project-config/2554a224551f8ce2b2748ee630fb496080b7468c/cedar-toml-schema-v2.0.json
#:tombi format.disabled = true

# This file contains the configuration settings for your Cedar app.
# This file is also what makes your Cedar app a Cedar app.
# If you remove it and try to run `yarn cedar dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: cedar.toml" doc:
# https://cedarjs.com/docs/app-configuration-cedar-toml

[web]
  title = "Cedar App"
  port = "${WEB_DEV_PORT:8910}"
  apiUrl = "/.redwood/functions"
  includeEnvironmentVariables = [
    # Add any ENV vars that should be available to the web side to this array
    # See https://cedarjs.com/docs/environment-variables#web
  ]
[api]
  port = "${API_DEV_PORT:8911}"
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]

[experimental.packagesWorkspace]
  enabled = true
