name: üè∑ Require release label

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

# Cancel in-progress runs of this workflow.
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# No top level permissions are required for this workflow
permissions: {}

jobs:
  require-release-label:
    name: üè∑ Require release label
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ‚¨¢ Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: 24

      - name: ‚úÖ Check release label requirement
        uses: ./.github/actions/require-release-label-or-cc-message
