name: ğŸ· Require release label

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

# We often cancel concurrent jobs, but this job is so fast it wouldn't really
# save any resources. It just complicates things (GitHub's runners would
# sometimes get confused, and get stuck waiting on an instance of this job that
# was canceled).

# No top level permissions are required for this workflow
permissions: {}

jobs:
  require-release-label:
    name: ğŸ· Require release label
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: â¬¢ Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 24

      - name: âœ… Check release label requirement
        uses: ./.github/actions/require-release-label-or-cc-message
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
